//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNVizeCarRentalApiSer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araba()
        {
            this.Kiralama = new HashSet<Kiralama>();
        }
    
        public string ArabaId { get; set; }
        public string ArabaMarkasi { get; set; }
        public string ArabaUcreti { get; set; }
        public string ArabaNo { get; set; }
        public bool ArabaDurum { get; set; }
        public string ArabaKatId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralama> Kiralama { get; set; }
    }
}
