//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İNVizeCarRentalApiSer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralama
    {
        public string KiralamaId { get; set; }
        public string KiralamaArabaId { get; set; }
        public string KiralamaUserId { get; set; }
        public System.DateTime KiralamaTarih { get; set; }
        public System.DateTime TeslimTarih { get; set; }
    
        public virtual Araba Araba { get; set; }
        public virtual User User { get; set; }
    }
}
